#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d term editor web files

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio              0.52
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config click_to_focus           false
bspc config focus_follows_pointer    true
bspc config pointer_follows_monitor  true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule --add Lxterminal  desktop='^1' follow=on
bspc rule --add Geany       desktop='^2' follow=on
bspc rule --add Firefox-esr desktop='^3' follow=on
bspc rule --add Pcmanfm     desktop='^4' follow=on
